//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMarket.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public int InquiryId { get; set; }
        public int RetailerId { get; set; }
        public int CustomerId { get; set; }
        public double Price { get; set; }
        public bool IsRejected { get; set; }
        public bool IsImageAttached { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Inquiry Inquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        public virtual User Customer { get; set; }
        public virtual User Retailer { get; set; }
    }
}
